
POST http://localhost:8080/api/bookings
Content-Type: application/json

{
  "workspace": {
    "id": 1
  },
  "tenantName": "Alex",
  "startTime": "2026-05-15T10:00:00",
  "endTime": "2026-05-15T12:00:00"
}

###

POST http://localhost:8080/api/bookings
Content-Type: application/json

{
  "workspace": {
    "id": 1
  },
  "tenantName": "Bob",
  "startTime": "2026-05-15T11:00:00",
  "endTime": "2026-05-15T13:00:00"
}